# 역전파

\begin{align}
z = x+y    \\
dL/dz = dL/dx + dL/dy  
\end{align}

\begin{equation*}
z = x+y    \\
dL/dz = dL/dx + dL/dy\\
\frac{\partial L}{\partial x}
\end{equation*}

\begin{equation*}
z = x+y\\
\frac{\partial L}{\partial z} = \frac{\partial L}{\partial x}+\frac{\partial L}{\partial y}
\end{equation*}

# 그래프를 쓰는 이유는 무엇인가? -> 이해가 쉽다는데 동의못하겠다
# 뒤돌아서 미분을 해주는 이유는 무엇인가?
# 역전파가 성립할 수 있는 이유는 무엇인가?

## 순전파와 역전파 이미지(repeat 노드, sum 노드)
<img src = './img/순전파와_역전파.jpg' style="transform: rotate(270deg);">  

In [4]:
import numpy as np

In [5]:
D, N = 8, 7
x = np.random.randn(1,D)

In [8]:
# 순전파
x

array([[ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775]])

In [9]:
x.shape

(1, 8)

### 가장 안에 있는 값의 axis 값이 가장 높다.

In [10]:
y = np.repeat(x, N, axis=0)

In [11]:
# 역전파
y

array([[ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775],
       [ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775],
       [ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775],
       [ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775],
       [ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775],
       [ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775],
       [ 0.14313535, -1.82790524, -0.07147578,  0.49407003, -0.6082377 ,
         0.15688175, -0.15593043,  0.52115775]])

In [12]:
dy = np.random.randn(N,D)
dx = np.sum(dy,axis=0, keepdims=True) # 이 경우 현재 2차원인데 sum에 1차원으로 바뀌는걸 방지해줌

In [13]:
dy

array([[-0.03690416, -1.07348377,  1.53248853, -1.55159005, -1.05772279,
         1.16495467, -1.45232343, -0.62277826],
       [-0.3067787 , -0.55467721, -0.44574984, -1.25460317,  0.26006134,
        -1.19124347,  1.01115503,  0.89999607],
       [ 1.4464099 , -2.28777549, -0.04253434,  1.22084919, -0.16720077,
        -0.28013026,  0.16358892,  1.35773292],
       [-0.78873084,  0.52959038, -0.36670594,  1.56158961, -0.80361708,
         0.53708323,  0.40209555, -1.07631153],
       [-2.28765259, -1.12955751, -0.51285947,  1.11431198,  0.73071438,
        -1.12734188, -0.01844683,  0.98616778],
       [ 0.14914817,  0.54558597,  0.62865654,  0.52633198, -0.36466838,
        -1.6566054 , -1.00300918, -0.16466118],
       [-1.14595401,  0.99851868,  0.09619565, -0.23566755,  1.34272305,
         0.29696397, -1.45024624,  0.3045113 ]])

In [14]:
dx

array([[-2.97046223, -2.97179895,  0.88949113,  1.38122198, -0.05971026,
        -2.25631914, -2.34718619,  1.68465709]])

#### 순방향
y = x matmul W
#### 역방향
\begin{equation*}

\end{equation*}